### ISSUE TITLE
Please make this available for all distros

### ISSUE THREAD

**Issue by surajmandalcell** [bcedu/ShutdownScheduler#13]
Linux is for everyone who want it right? so why not the software’s in it

**Comment by bcedu** [comment]
@surajmandalcell I'm working on make a flatpak, but it will be a long process. By now, I think you culd check the [.deb file](https://github.com/bcedu/ShutdownScheduler/releases/tag/v1.2.1) that I attached to the las release. It should work in any debian based distro.

**Comment by surajmandalcell** [comment]
@bcedu  it think uses granite so you sure it is ready for all distros?
