### ISSUE TITLE
Change requested: missing AppStream release data for 1.3.1

### ISSUE THREAD

**Issue by cassidyjames** [bcedu/ShutdownScheduler#17]
Thanks for publishing an update to AppCenter! However, I have to request a change before it can be released to users: the 1.3.1 release is missing AppStream release data describing the change. This is required for all updates so users can see what is being updated. Please publish a new release (i.e. 1.3.2) with this data describing the fix. Let me know if you have any questions!

**Comment by bcedu** [comment]
Closed by 77c85051ca6f9b5a3690640a0ffb3db3dd7ae876
