### ISSUE TITLE
Window is too big

### ISSUE THREAD

**Issue by NathanBnm** [bcedu/ShutdownScheduler#23]
I was surprised when I opened the app just after the update, it's look like this:

![image](https://user-images.githubusercontent.com/45366162/57473444-1e41da00-7290-11e9-9f4c-84b00548568a.png)

I guess it's not supposed to make this size, the way that the buttons are looking with this size is very ugly :o

**Comment by bcedu** [comment]
The windows is now resizable and it remembers the las size you put. You can change it how you like :)

**Comment by NathanBnm** [comment]
Sure! But you should add a default size, because when it opens like that it looks very strange I think.
