### ISSUE TITLE
Make buttons always circle

### ISSUE THREAD

**Issue by NathanBnm** [bcedu/ShutdownScheduler#38]
Do you think there is some way to implement this? Like at the app startup:

![image](https://user-images.githubusercontent.com/45366162/58895790-0de91780-86f5-11e9-84f9-9ae237f98037.png)

I think it's looking weird and not very aesthetic when you resize the window. Just see the following screenshots:

![image](https://user-images.githubusercontent.com/45366162/58895862-2ce7a980-86f5-11e9-9be4-13e19daa347a.png)
![image](https://user-images.githubusercontent.com/45366162/58895919-47218780-86f5-11e9-99ed-f64c67b079cb.png)

**Comment by bcedu** [comment]
The only solution I've found is fixing the window size.

I tried with `set_geometry_hints` passing an aspect ratio it doesn't work well, when i resized the window it moved randomly with nonsense.

Do you think it would be better to fix the windows size?

**Comment by NathanBnm** [comment]
I think yes. In my opinion there is no interest for this app to be resized. It's like a widget, I think it's more reliable if it stays with a small fixer size. What do you think?

**Comment by bcedu** [comment]
Done with e2727c08a03196b2eab295edb9a7cbf6886435a9
